name: karaoke
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # UI & Utilities
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.4
  permission_handler: ^11.3.0
  logger: ^2.0.0

  # State Management
  provider: ^6.1.1
  get_it: ^7.6.7

  # Networking
  dio: ^5.4.1
  json_annotation: 4.8.1

  # Audio
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  audioplayers: ^6.0.0
  timeago: ^3.6.1

  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.5.4
  share_plus: ^12.0.1
  http: ^1.6.0
  rxdart: ^0.28.0
  scroll_to_index: ^3.0.1
  supabase_flutter: ^2.12.0
  google_sign_in: ^6.1.0

  shimmer: ^3.0.0
  wakelock_plus: ^1.2.8
  jwt_decoder: ^2.0.1

  record: ^6.1.2
  record_linux: ^1.2.0
  path_provider: ^2.1.2
  uuid: ^4.5.2

  onesignal_flutter: ^5.0.0
  universal_html: ^2.3.0

  flutter_dotenv: ^5.1.0
  image_picker: ^1.2.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

  flutter_launcher_icons: ^0.13.1

  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google.png
    - .env

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icon_app.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon_app.png"
    background_color: "#1A0E7E"
    theme_color: "#1A0E7E"

flutter_native_splash:
  color: "#1A0E7E"
  image: assets/logo.png

  fullscreen: true

  android_12:
    icon_background_color: "#1A0E7E"
    image: assets/logo.png